// Email Builder - Barrel Exports

export { EmailBuilderProvider, useEmailBuilder } from './EmailBuilderContext'
export type { EmailElement, TemplateSettings } from './EmailBuilderContext'
export { generateEmailHtml, parseEmailHtml } from './html-utils'
export { EmailBuilderDndWrapper, useDndDragState } from './EmailBuilderDndWrapper'
export type { SidebarDragData, CanvasDragData, DragData } from './EmailBuilderDndWrapper'
export { DraggableSidebarItem } from './DraggableSidebarItem'
export { EmailBuilderSidebar } from './EmailBuilderSidebar'
export { SortableCanvasElement } from './SortableCanvasElement'
export { DragOverlayContent } from './DragOverlayContent'
export { DropIndicator } from './DropIndicator'
export { EmailBuilderToolbar } from './EmailBuilderToolbar'
export { EmailBuilderCanvas } from './EmailBuilderCanvas'
export { EmailBuilderProperties } from './EmailBuilderProperties'
export { LanguageSelector, SUPPORTED_LOCALES } from './LanguageSelector'
export type { LanguageSelectorProps } from './LanguageSelector'
export { VariablePicker } from './VariablePicker'
export { DEFAULT_CATEGORIES } from './VariablePicker'
export type { VariablePickerProps, VariableCategory, VariableItem } from './VariablePicker'
